import { readdir, readFile, writeFile, mkdir } from "fs/promises";
import { join, relative } from "path";
import { existsSync } from "fs";

const ROOT = process.cwd();
const EMBEDS = join(ROOT, "embeds");
const SANDBOX_DIR = join(EMBEDS, "sandbox");
const PREVIEWS_DIR = join(EMBEDS, "previews");
const OUT_SANDBOX = join(ROOT, "public", "l");
const OUT_PREVIEWS = join(ROOT, "public", "r");
const REGISTRY_OUT = join(ROOT, "lib", "preview-registry.generated.ts");

async function walkDirectory(dir: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDirectory(fullPath)));
    } else {
      files.push(fullPath);
    }
  }

  return files;
}

async function generateSandboxBundles() {
  if (!existsSync(SANDBOX_DIR)) {
    console.warn(
      `[generate-sources] No ${SANDBOX_DIR}; create embeds/sandbox/<id>/ for Sandpack bundles.`
    );
    return;
  }

  await mkdir(OUT_SANDBOX, { recursive: true });

  const entries = await readdir(SANDBOX_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) continue;

    const id = entry.name;
    const bundlePath = join(SANDBOX_DIR, id);
    const filePaths = await walkDirectory(bundlePath);
    const files: { name: string; content: string }[] = [];

    for (const filePath of filePaths) {
      const rel = relative(bundlePath, filePath);
      const content = await readFile(filePath, "utf-8");
      files.push({ name: rel, content });
    }

    const jsonData = { demo: id, files };
    const outFile = join(OUT_SANDBOX, `${id}.json`);
    await writeFile(outFile, JSON.stringify(jsonData, null, 2));
    console.log(`[sandbox] public/l/${id}.json`);
  }
}

async function writeEmptyRegistry(reason: string) {
  await mkdir(join(ROOT, "lib"), { recursive: true });
  await writeFile(
    REGISTRY_OUT,
    `// Generated by scripts/generate-sources.ts — ${reason}
import type { ComponentType } from "react";

export const previewRegistry: Record<string, ComponentType<object>> = {};
`
  );
  console.log(`[preview] ${relative(ROOT, REGISTRY_OUT)} (empty)`);
}

async function generatePreviews() {
  await mkdir(OUT_PREVIEWS, { recursive: true });

  if (!existsSync(PREVIEWS_DIR)) {
    await mkdir(PREVIEWS_DIR, { recursive: true });
    await writeEmptyRegistry("create embeds/previews/<name>/index.tsx");
    console.warn(
      `[generate-sources] Created ${PREVIEWS_DIR}; add embeds/previews/<name>/index.tsx for inline demos.`
    );
    return;
  }

  const entries = await readdir(PREVIEWS_DIR, { withFileTypes: true });
  const previewNames: string[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
    const name = entry.name;
    const indexTsx = join(PREVIEWS_DIR, name, "index.tsx");
    if (!existsSync(indexTsx)) {
      console.warn(
        `[generate-sources] Skipping "${name}": missing index.tsx`
      );
      continue;
    }

    const dirPath = join(PREVIEWS_DIR, name);
    const filePaths = await walkDirectory(dirPath);
    const files: { path: string; content: string }[] = [];

    for (const filePath of filePaths) {
      const rel = relative(dirPath, filePath).split("\\").join("/");
      const content = await readFile(filePath, "utf-8");
      files.push({ path: rel, content });
    }

    const jsonData = { name, files };
    await writeFile(
      join(OUT_PREVIEWS, `${name}.json`),
      JSON.stringify(jsonData, null, 2)
    );
    console.log(`[preview] public/r/${name}.json`);

    previewNames.push(name);
  }

  await mkdir(join(ROOT, "lib"), { recursive: true });

  if (previewNames.length === 0) {
    await writeEmptyRegistry("no valid embeds/previews/*/index.tsx");
    return;
  }

  const importLines = previewNames
    .map(
      (name, i) =>
        `import Preview${i} from "@/embeds/previews/${name}";`
    )
    .join("\n");

  const registryLines = previewNames
    .map((name, i) => `  ${JSON.stringify(name)}: Preview${i}`)
    .join(",\n");

  const source = `/* eslint-disable import/no-default-export */
// Generated by scripts/generate-sources.ts — do not edit by hand.
import type { ComponentType } from "react";
${importLines}

export const previewRegistry: Record<string, ComponentType<object>> = {
${registryLines}
};
`;

  await writeFile(REGISTRY_OUT, source);
  console.log(`[preview] ${relative(ROOT, REGISTRY_OUT)}`);
}

async function main() {
  await mkdir(EMBEDS, { recursive: true });
  await generateSandboxBundles();
  await generatePreviews();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
