/**
 * Converts authoring MDX (`site/content/docs/*.mdx`, `dev.mdx`) into plain Markdown
 * for `*.md` HTTP routes (agents, raw docs).
 *
 * Runs as part of `pnpm run generate-sources` (site build), or alone via `pnpm run generate-agent-md`.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  DOC_MARKDOWN_SOURCE_MDX,
  type MarkdownDocSegment,
} from "../lib/doc-markdown-source";

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "content", "generated", "agent");

const GENERATED_HEADER =
  "<!-- Generated by scripts/generate-agent-markdown.ts — do not edit by hand. -->\n\n";

function skipWs(s: string, i: number): number {
  while (i < s.length && /\s/.test(s[i]!)) i++;
  return i;
}

function parseStringLiteral(
  s: string,
  i: number,
): { end: number; value: string } | null {
  const q = s[i];
  if (q !== '"' && q !== "'") return null;
  let j = i + 1;
  let value = "";
  while (j < s.length) {
    const c = s[j]!;
    if (c === "\\") {
      value += s[j + 1] ?? "";
      j += 2;
      continue;
    }
    if (c === q) return { end: j + 1, value };
    value += c;
    j++;
  }
  return null;
}

function parseTemplateLiteral(
  s: string,
  i: number,
): { end: number; value: string } | null {
  if (s[i] !== "`") return null;
  let j = i + 1;
  let value = "";
  while (j < s.length) {
    const c = s[j]!;
    if (c === "\\") {
      value += s[j + 1] ?? "";
      j += 2;
      continue;
    }
    if (c === "`") return { end: j + 1, value };
    value += c;
    j++;
  }
  return null;
}

function scanOpeningAngleClosingGT(src: string, ltIdx: number): number {
  let i = ltIdx + 1;
  let quote: "'" | '"' | null = null;
  while (i < src.length) {
    const c = src[i]!;
    if (quote) {
      if (c === "\\") {
        i += 2;
        continue;
      }
      if (c === quote) quote = null;
      i++;
      continue;
    }
    if (c === '"' || c === "'") {
      quote = c;
      i++;
      continue;
    }
    if (c === ">") return i + 1;
    i++;
  }
  return -1;
}

/** `{ … }` with nested JSX/strings/templates — ignores `{`/`}` inside strings / templates. */
function skipBalancedBraceExpression(src: string, start: number): number {
  if (src[start] !== "{") {
    throw new Error("generate-agent-markdown: skipBalancedBraceExpression expected {");
  }
  let depth = 0;
  let i = start;
  while (i < src.length) {
    const c = src[i]!;
    if (c === '"' || c === "'") {
      const p = parseStringLiteral(src, i);
      if (!p) throw new Error("generate-agent-markdown: bad string inside JSX expr");
      i = p.end;
      continue;
    }
    if (c === "`") {
      const tl = parseTemplateLiteral(src, i);
      if (!tl) throw new Error("generate-agent-markdown: bad template inside JSX expr");
      i = tl.end;
      continue;
    }
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      i++;
      if (depth === 0) return i;
      continue;
    }
    i++;
  }
  throw new Error("generate-agent-markdown: unterminated JSX expression");
}

/** End index immediately after `>` or `/>` — handles attrs such as `defaultValue={<em>…</em>}`. */
function jsxOpeningTagEnd(src: string, ltIdx: number): number {
  let i = ltIdx + 1;
  if (src[i] === "/") return -1;
  while (i < src.length && /[\w:]/.test(src[i]!)) i++;

  while (i < src.length) {
    i = skipWs(src, i);
    if (src[i] === "/" && src[i + 1] === ">") return i + 2;
    if (src[i] === ">") return i + 1;

    const nameStart = i;
    while (i < src.length && /[\w:-]/.test(src[i]!)) i++;
    if (i === nameStart) {
      throw new Error(`generate-agent-markdown: malformed JSX tag near ${ltIdx}`);
    }
    i = skipWs(src, i);
    if (src[i] !== "=") {
      throw new Error(`generate-agent-markdown: expected = after JSX attribute`);
    }
    i++;
    i = skipWs(src, i);
    if (src[i] === '"' || src[i] === "'") {
      const p = parseStringLiteral(src, i);
      if (!p) throw new Error("generate-agent-markdown: bad JSX attribute string");
      i = p.end;
      continue;
    }
    if (src[i] === "{") {
      i = skipBalancedBraceExpression(src, i);
      continue;
    }
    throw new Error(`generate-agent-markdown: unsupported JSX attribute value at ${i}`);
  }
  return -1;
}

function extractQuoted(attrs: string, key: string): string | null {
  const re = new RegExp(`${key}="([^"]*)"`);
  const m = re.exec(attrs);
  return m?.[1] ?? null;
}

function jsxInnerText(s: string): string {
  return s.replace(/<[^>]+>/g, "").trim();
}

function extractDefaultValue(attrs: string): string {
  const key = "defaultValue=";
  const idx = attrs.indexOf(key);
  if (idx === -1) return "";
  let pos = idx + key.length;
  pos = skipWs(attrs, pos);
  const sq = parseStringLiteral(attrs, pos);
  if (sq) return sq.value;
  if (attrs[pos] !== "{") return "";
  let depth = 0;
  const start = pos;
  for (let i = pos; i < attrs.length; i++) {
    const c = attrs[i]!;
    if (c === '"' || c === "'") {
      const q = c;
      let j = i + 1;
      while (j < attrs.length) {
        if (attrs[j] === "\\") {
          j += 2;
          continue;
        }
        if (attrs[j] === q) {
          i = j;
          break;
        }
        j++;
      }
      continue;
    }
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        const inner = attrs.slice(start + 1, i);
        return jsxInnerText(inner);
      }
    }
  }
  return "";
}

function escapeCell(s: string): string {
  return s.replace(/\r\n/g, "\n").replace(/\n+/g, " ").replace(/\|/g, "\\|").trim();
}

function normalizeDescBlock(body: string): string {
  return body.replace(/\r\n/g, "\n").replace(/\s+/g, " ").trim();
}

function parseCodeSnippetBlock(
  src: string,
  at: number,
): { end: number; md: string } | null {
  if (!src.startsWith("<CodeSnippet", at)) return null;
  let pos = at + "<CodeSnippet".length;
  let title: string | undefined;
  let language = "typescript";
  let code: string | undefined;

  while (true) {
    pos = skipWs(src, pos);
    if (src[pos] === "/" && src[pos + 1] === ">") {
      pos += 2;
      break;
    }
    const rest = src.slice(pos);
    const nameMatch = /^([a-zA-Z][a-zA-Z0-9]*)/.exec(rest);
    if (!nameMatch) {
      throw new Error(`generate-agent-markdown: malformed CodeSnippet near ${pos}`);
    }
    const attrName = nameMatch[1]!;
    pos += attrName.length;
    pos = skipWs(src, pos);
    if (src[pos] !== "=") {
      throw new Error(`generate-agent-markdown: expected = after ${attrName}`);
    }
    pos++;
    pos = skipWs(src, pos);

    if (attrName === "code") {
      if (src[pos] !== "{") {
        throw new Error("generate-agent-markdown: expected code={");
      }
      pos++;
      pos = skipWs(src, pos);
      const tl = parseTemplateLiteral(src, pos);
      if (!tl) throw new Error("generate-agent-markdown: bad code template literal");
      code = tl.value;
      pos = tl.end;
      pos = skipWs(src, pos);
      if (src[pos] !== "}") {
        throw new Error("generate-agent-markdown: expected } after code template");
      }
      pos++;
    } else if (src[pos] === '"' || src[pos] === "'") {
      const str = parseStringLiteral(src, pos);
      if (!str) throw new Error(`generate-agent-markdown: bad string for ${attrName}`);
      pos = str.end;
      if (attrName === "title") title = str.value;
      if (attrName === "language") language = str.value;
    } else {
      throw new Error(`generate-agent-markdown: unsupported CodeSnippet attr ${attrName}`);
    }
  }

  const fence = language || "text";
  const head = title ? `**${title}**\n\n` : "";
  const body = (code ?? "").replace(/^\n+/, "").replace(/\s+$/, "");
  const md = `${head}\`\`\`${fence}\n${body}\n\`\`\`\n`;
  return { end: pos, md };
}

function replaceCodeSnippets(src: string): string {
  let out = "";
  let i = 0;
  while (i < src.length) {
    const idx = src.indexOf("<CodeSnippet", i);
    if (idx === -1) return out + src.slice(i);
    out += src.slice(i, idx);
    const parsed = parseCodeSnippetBlock(src, idx);
    if (!parsed) {
      out += src[idx]!;
      i = idx + 1;
      continue;
    }
    out += parsed.md;
    i = parsed.end;
  }
  return out;
}

function apiPropListInnerToMd(inner: string): string {
  const rows: { name: string; type: string; def: string; desc: string }[] = [];
  let pos = 0;
  while (true) {
    pos = skipWs(inner, pos);
    if (pos >= inner.length) break;
    if (!inner.startsWith("<ApiProp", pos)) break;

    const openEnd = jsxOpeningTagEnd(inner, pos);
    if (openEnd === -1) {
      throw new Error("generate-agent-markdown: unclosed <ApiProp opening tag");
    }
    const attrs = inner.slice(pos + "<ApiProp".length, openEnd - 1).trim();
    const name = extractQuoted(attrs, "name") ?? "";
    const typ = extractQuoted(attrs, "type") ?? "";
    const defRaw = extractDefaultValue(attrs);
    const closeIdx = inner.indexOf("</ApiProp>", openEnd);
    if (closeIdx === -1) throw new Error("generate-agent-markdown: missing </ApiProp>");
    const body = inner.slice(openEnd, closeIdx).trim();
    const desc = normalizeDescBlock(body);
    rows.push({
      name,
      type: typ,
      def: defRaw,
      desc,
    });
    pos = closeIdx + "</ApiProp>".length;
  }

  const header =
    "\n| Property | Type | Default | Description |\n| --- | --- | --- | --- |\n";
  const lines = rows.map(
    (r) =>
      `| ${escapeCell(r.name)} | ${escapeCell(r.type)} | ${escapeCell(r.def)} | ${escapeCell(r.desc)} |`,
  );
  return `\n${header}${lines.join("\n")}\n\n`;
}

function replaceApiPropLists(src: string): string {
  let out = "";
  let i = 0;
  while (true) {
    const idx = src.indexOf("<ApiPropList", i);
    if (idx === -1) return out + src.slice(i);
    out += src.slice(i, idx);
    const openEnd = scanOpeningAngleClosingGT(src, idx);
    if (openEnd === -1) {
      throw new Error("generate-agent-markdown: unclosed <ApiPropList> opening");
    }
    const closeIdx = src.indexOf("</ApiPropList>", openEnd);
    if (closeIdx === -1) {
      throw new Error("generate-agent-markdown: missing </ApiPropList>");
    }
    const inner = src.slice(openEnd, closeIdx);
    out += apiPropListInnerToMd(inner);
    i = closeIdx + "</ApiPropList>".length;
  }
}

function extractPreviewAttrs(block: string): { name: string; description: string } {
  const name = extractQuoted(block, "name") ?? "";
  const desc = extractQuoted(block, "description") ?? "";
  return { name, description: desc };
}

function replacePreviewBlocks(src: string): string {
  const marker = "<Preview";
  let out = "";
  let i = 0;
  while (true) {
    const idx = src.indexOf(marker, i);
    if (idx === -1) return out + src.slice(i);
    out += src.slice(i, idx);
    const close = src.indexOf("/>", idx);
    if (close === -1) throw new Error("generate-agent-markdown: unclosed <Preview />");
    const block = src.slice(idx, close + 2);
    const { name, description } = extractPreviewAttrs(block);
    const line = description
      ? `**Interactive demo (\`${name}\`):** ${description}\n\n`
      : `**Interactive demo:** \`${name}\`\n\n`;
    out += line;
    i = close + 2;
  }
}

function replaceSandboxBlocks(src: string): string {
  const re = /<Sandbox\s+demo="([^"]+)"\s*\/>/g;
  let s = src.replace(
    re,
    (_, demo: string) =>
      `**Sandbox (\`${demo}\`):** bundled sources are published at \`/l/${demo}.json\` on the docs site.\n\n`,
  );
  const reName = /<Sandbox\s+name="([^"]+)"\s*\/>/g;
  s = s.replace(
    reName,
    (_, name: string) =>
      `**Sandbox (\`${name}\`):** bundled sources are published at \`/l/${name}.json\` on the docs site.\n\n`,
  );
  return s;
}

function replaceInstallTabs(src: string): string {
  return src.replace(
    /<InstallTabs\s+command="([^"]+)"(?:\s+npx=\{(?:true|false)\})?\s*\/>/g,
    (_, cmd: string) =>
      [
        "**Install**",
        "",
        "```bash",
        `pnpm add ${cmd}`,
        `npm i ${cmd}`,
        `yarn add ${cmd}`,
        `bun add ${cmd}`,
        "```",
        "",
      ].join("\n"),
  );
}

function replaceDocMobileHoverNotice(src: string): string {
  return src.replace(
    /<DocMobileHoverNotice\s*\/>/g,
    "> This library and the live demos work best on desktop with a mouse or trackpad.\n\n",
  );
}

function replaceDocCodeHeading(src: string): string {
  return src.replace(
    /<DocCodeHeading\s+id="[^"]*"\s*>([\s\S]*?)<\/DocCodeHeading>/g,
    (_, title: string) => `### ${title.trim()}\n\n`,
  );
}

export function mdxSourceToAgentMarkdown(src: string): string {
  let s = src;
  s = replaceCodeSnippets(s);
  s = replaceApiPropLists(s);
  s = replacePreviewBlocks(s);
  s = replaceSandboxBlocks(s);
  s = replaceInstallTabs(s);
  s = replaceDocMobileHoverNotice(s);
  s = replaceDocCodeHeading(s);
  return s.trim() + "\n";
}

export async function generateAgentMarkdownDocs(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const segments = Object.keys(DOC_MARKDOWN_SOURCE_MDX) as MarkdownDocSegment[];

  for (const segment of segments) {
    const relSource = DOC_MARKDOWN_SOURCE_MDX[segment];
    const absIn = path.join(ROOT, "content", relSource);
    const raw = await readFile(absIn, "utf8");
    const md = GENERATED_HEADER + mdxSourceToAgentMarkdown(raw);
    const outName = segment;
    const absOut = path.join(OUT_DIR, outName);
    await writeFile(absOut, md, "utf8");
    console.log(`[agent-md] ${path.relative(ROOT, absOut)}`);
  }
}

