/* eslint-disable import/no-default-export */
// Generated by scripts/generate-sources.ts — do not edit by hand.
import type { ComponentType } from "react";
import Preview0 from "@/embeds/previews/scroll-list";

export const previewRegistry: Record<string, ComponentType<object>> = {
  "scroll-list": Preview0
};
